FROM node:16-alpine

RUN mkdir -p /home/app
COPY . /home/app
RUN cd /home/app && npm install && npm run build

ARG SOCKET_URI 

ENV REACT_APP_HOST_API_GATEWAY=$SOCKET_URI

EXPOSE 3000 

CMD ["node", "/home/app/index.js"]