FROM node:16.19-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install 
COPY . .

RUN npm install serve -g
RUN npm run build

ARG PORT_GATEWAY
ARG DOMAIN_GATEWAY

ENV REACT_APP_PORT_API_GATEWAY=$PORT_GATEWAY
ENV REACT_APP_DOMAIN_API_GATEWAY=$POMAIN_GATEWAY

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]